package com.csd.farm.auth;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.jdbc.support.GeneratedKeyHolder;

@Repository
public class FarmerRepository implements UserDetailsService {
    private final JdbcClient jdbc;
    private final String table, id, name, email, hash;

    public FarmerRepository(JdbcClient jdbc,
            @Value("${app.users.schema:public}") String schema,
            @Value("${app.users.table:USERS}") String table,
            @Value("${app.users.id:User_ID}") String id,
            @Value("${app.users.name:User_Name}") String name,
            @Value("${app.users.email:User_Email}") String email,
            @Value("${app.users.hash:Password_Hash}") String hash) {
        this.jdbc = jdbc;
        this.table = quote(schema) + "." + quote(table);
        this.id = quote(id);
        this.name = quote(name);
        this.email = quote(email);
        this.hash = quote(hash);
    }

    // Only server configuration supplies identifiers; all values use bound parameters.
    private static String quote(String value) {
        if (!value.matches("[A-Za-z_][A-Za-z0-9_]*")) {
            throw new IllegalArgumentException("Invalid user-table SQL identifier in configuration");
        }
        return "\"" + value + "\"";
    }

    @Transactional
    public Farmer save(Farmer farmer, String passwordHash) {
        var keys = new GeneratedKeyHolder();
        jdbc.sql("INSERT INTO " + table + " (" + name + ", " + email + ", " + hash
                + ") VALUES (:name, :email, :hash)")
                .param("name", farmer.username()).param("email", farmer.email())
                .param("hash", passwordHash).update(keys, id.substring(1, id.length() - 1));
        Number key = keys.getKey();
        if (key == null) throw new IllegalStateException("User_ID must be generated by the database");
        Long farmerId = key.longValue();
        jdbc.sql("INSERT INTO farm.account_status (farmer_id, email_verified) VALUES (:id, FALSE)")
                .param("id", farmerId).update();
        return new Farmer(farmerId, farmer.username(), farmer.email(), false);
    }
    private String select() {
        return "SELECT u." + id + " AS id, u." + name + " AS username, u." + email
                + " AS email, COALESCE(s.email_verified, FALSE) AS email_verified FROM " + table
                + " u LEFT JOIN farm.account_status s ON s.farmer_id = u." + id;
    }

    private Farmer map(ResultSet row, int number) throws SQLException {
        return new Farmer(row.getLong("id"), row.getString("username"),
                row.getString("email"), row.getBoolean("email_verified"));
    }

    public Optional<Farmer> findByUsername(String username) {
        return jdbc.sql(select() + " WHERE u." + name + " = :value")
                .param("value", username).query(this::map).optional();
    }

    public Optional<Farmer> findByEmail(String address) {
        return jdbc.sql(select() + " WHERE u." + email + " = :value")
                .param("value", address).query(this::map).optional();
    }

    public void markEmailVerified(Long farmerId) {
        jdbc.sql("UPDATE farm.account_status SET email_verified = TRUE WHERE farmer_id = :id")
                .param("id", farmerId).update();
    }

    public void updatePassword(Long farmerId, String passwordHash) {
        jdbc.sql("UPDATE " + table + " SET " + hash + " = :hash WHERE " + id + " = :id")
                .param("id", farmerId).param("hash", passwordHash).update();
    }

    @Override
    public UserDetails loadUserByUsername(String username) {
        return jdbc.sql("SELECT " + name + " AS username, " + hash + " AS password_hash FROM "
                + table + " WHERE " + name + " = :name")
                .param("name", username)
                .query((row, number) -> User.withUsername(row.getString("username"))
                        .password(row.getString("password_hash")).roles("FARMER").build())
                .optional().orElseThrow(() -> new UsernameNotFoundException("Invalid username or password."));
    }
}


