CREATE SCHEMA IF NOT EXISTS farm;
-- CREATE SCHEMA IF NOT EXISTS farm;
        -- for later, persistent implementation

CREATE TABLE public."USERS" (
    "User_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 3000000000) PRIMARY KEY,
    "User_Name" VARCHAR(40) NOT NULL UNIQUE,
    "User_Email" VARCHAR(320) NOT NULL UNIQUE,
    "Password_Hash" VARCHAR(255) NOT NULL
);

CREATE TABLE farm.account_status (
    farmer_id BIGINT PRIMARY KEY REFERENCES public."USERS"("User_ID") ON DELETE CASCADE,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE farm.account_token (
    id UUID PRIMARY KEY,
    farmer_id BIGINT NOT NULL
        REFERENCES public."USERS"("User_ID") ON DELETE CASCADE,
    purpose VARCHAR(30) NOT NULL
        CHECK (purpose IN ('EMAIL_VERIFY', 'PASSWORD_RESET')),
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE farm.crop_entry (
    farmer_id BIGINT NOT NULL 
        REFERENCES public."USERS"("User_ID")
        ON DELETE CASCADE,
    crop_type VARCHAR(30) NOT NULL,
    planted_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    latitude NUMERIC(9, 6) NOT NULL 
        CHECK (latitude BETWEEN -90 AND 90),
    longitude NUMERIC(9, 6) NOT NULL 
        CHECK (longitude BETWEEN -180 AND 180),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL 
        DEFAULT CURRENT_TIMESTAMP,

    -- A farmer has many entries. Different farmers can plant the same crop at the same time.
    PRIMARY KEY (farmer_id, crop_type, planted_at),

    CHECK (crop_type IN (
        'POTATO', 'SUGAR_CANE', 'APPLE', 'RICE', 'WHEAT',
        'MAIZE', 'TOMATO', 'CARROT', 'LETTUCE', 'SOYBEAN'
    ))
);

CREATE INDEX crop_entry_farmer_index 
    ON farm.crop_entry (farmer_id, planted_at);

-- The demo creates its schema directly instead of running the weather migrations.
ALTER TABLE farm.crop_entry ADD COLUMN weather_date DATE;
ALTER TABLE farm.crop_entry ADD COLUMN weather_timezone VARCHAR(100);

ALTER TABLE farm.crop_entry ADD COLUMN temperature_mean_c DOUBLE PRECISION
    CHECK (temperature_mean_c BETWEEN -100 AND 100);

ALTER TABLE farm.crop_entry ADD COLUMN sunshine_duration_seconds DOUBLE PRECISION
    CHECK (sunshine_duration_seconds BETWEEN 0 AND 86400);

ALTER TABLE farm.crop_entry ADD COLUMN humidity_mean_percent DOUBLE PRECISION
    CHECK (humidity_mean_percent BETWEEN 0 AND 100);

ALTER TABLE farm.crop_entry ADD COLUMN soil_moisture_mean_m3m3 DOUBLE PRECISION
    CHECK (soil_moisture_mean_m3m3 BETWEEN 0 AND 1);

ALTER TABLE farm.crop_entry ADD COLUMN weather_source VARCHAR(20)
    NOT NULL DEFAULT 'MANUAL'
    CHECK (weather_source IN ('MANUAL', 'OPEN_METEO'));


